spring.application.name=House
server.port=9000
# mapstruct
mapstruct.defaultComponentModel=spring

# BD LOCAL
#BD local
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

#security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG

#email send
spring.mail.host=${HOST_SENDER}
spring.mail.port=${PORT_SENDER}
spring.mail.username=${EMAIL_SENDER}
spring.mail.password=${PASSWORD_SENDER}
spring.mail.properties.mail.smpt.auth=true
spring.mail.properties.mail.smtp.starttls.enable =true