spring:
  application:
    name: discovery-server
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    org.springframework.cloud.gateway: DEBUG